# Generated by Django 3.2.15 on 2022-11-18 06:12

import arches.app.models.fields.i18n
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8974_rr_load_performance_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardxnodexwidget',
            name='config',
            field=arches.app.models.fields.i18n.I18n_JSONField(blank=True, db_column='config', null=True),
        ),
        migrations.AlterField(
            model_name='ddatatype',
            name='defaultconfig',
            field=arches.app.models.fields.i18n.I18n_JSONField(blank=True, db_column='defaultconfig', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='config',
            field=arches.app.models.fields.i18n.I18n_JSONField(blank=True, db_column='config', null=True),
        ),
        migrations.AlterField(
            model_name='publishedgraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publishedgraph',
            name='serialized_graph',
            field=models.JSONField(blank=True, db_column='serialized_graph', null=True),
        ),
        migrations.AlterField(
            model_name='resourceinstance',
            name='descriptors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
